export const 
    PAGELIST = "PAGELIST", 
    PAGEERROR = "PAGEERROR",
    PAGEUPDATE = "PAGEUPDATE",
    PAGELOAD = "PAGELOAD",
    PAGERETRY = "PAGERETRY",
    OPENREQUEST = "OPENREQUEST",
    OPENSUCCESS = "OPENSUCCESS"
;